import { vi } from 'vitest'

import type { saveToGoogleDrive as SaveToGoogleDrive } from '../lib/imports/google-drive-save'

/** Shared provider boundary; each route still asserts its own generated bytes and completion state. */
export const saveToGoogleDrive = vi.fn<typeof SaveToGoogleDrive>()
