/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppBulkRouteImport } from './routes/app/bulk'
import { Route as AppEditorRouteImport } from './routes/app/editor'
import { Route as AppGalleryRouteImport } from './routes/app/gallery'
import { Route as AppMembersRouteImport } from './routes/app/members'
import { Route as AppSharesRouteImport } from './routes/app/shares'
import { Route as AppVerifyRouteImport } from './routes/app/verify'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as AppLibraryIndexRouteImport } from './routes/app/library/index'
import { Route as AppLibraryWatermarkIdRouteImport } from './routes/app/library/$watermarkId'
import { Route as AppLibraryNewRouteImport } from './routes/app/library/new'
import { Route as AppOrganizationsNewRouteImport } from './routes/app/organizations/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBulkRoute = AppBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMembersRoute = AppMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSharesRoute = AppSharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVerifyRoute = AppVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AppRouteRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLibraryIndexRoute = AppLibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryWatermarkIdRoute = AppLibraryWatermarkIdRouteImport.update({
  id: '/library/$watermarkId',
  path: '/library/$watermarkId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibraryNewRoute = AppLibraryNewRouteImport.update({
  id: '/library/new',
  path: '/library/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrganizationsNewRoute = AppOrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/admin': typeof AppAdminRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bulk': typeof AppBulkRoute
  '/app/editor': typeof AppEditorRoute
  '/app/gallery': typeof AppGalleryRoute
  '/app/members': typeof AppMembersRoute
  '/app/shares': typeof AppSharesRoute
  '/app/verify': typeof AppVerifyRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/library/$watermarkId': typeof AppLibraryWatermarkIdRoute
  '/app/library/new': typeof AppLibraryNewRoute
  '/app/organizations/new': typeof AppOrganizationsNewRoute
  '/app/library/': typeof AppLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-email': typeof CheckEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/admin': typeof AppAdminRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bulk': typeof AppBulkRoute
  '/app/editor': typeof AppEditorRoute
  '/app/gallery': typeof AppGalleryRoute
  '/app/members': typeof AppMembersRoute
  '/app/shares': typeof AppSharesRoute
  '/app/verify': typeof AppVerifyRoute
  '/share/$token': typeof ShareTokenRoute
  '/app': typeof AppIndexRoute
  '/app/library/$watermarkId': typeof AppLibraryWatermarkIdRoute
  '/app/library/new': typeof AppLibraryNewRoute
  '/app/organizations/new': typeof AppOrganizationsNewRoute
  '/app/library': typeof AppLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/admin': typeof AppAdminRoute
  '/app/audit': typeof AppAuditRoute
  '/app/bulk': typeof AppBulkRoute
  '/app/editor': typeof AppEditorRoute
  '/app/gallery': typeof AppGalleryRoute
  '/app/members': typeof AppMembersRoute
  '/app/shares': typeof AppSharesRoute
  '/app/verify': typeof AppVerifyRoute
  '/share/$token': typeof ShareTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/library/$watermarkId': typeof AppLibraryWatermarkIdRoute
  '/app/library/new': typeof AppLibraryNewRoute
  '/app/organizations/new': typeof AppOrganizationsNewRoute
  '/app/library/': typeof AppLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/app/admin'
    | '/app/audit'
    | '/app/bulk'
    | '/app/editor'
    | '/app/gallery'
    | '/app/members'
    | '/app/shares'
    | '/app/verify'
    | '/share/$token'
    | '/app/'
    | '/app/library/$watermarkId'
    | '/app/library/new'
    | '/app/organizations/new'
    | '/app/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/app/admin'
    | '/app/audit'
    | '/app/bulk'
    | '/app/editor'
    | '/app/gallery'
    | '/app/members'
    | '/app/shares'
    | '/app/verify'
    | '/share/$token'
    | '/app'
    | '/app/library/$watermarkId'
    | '/app/library/new'
    | '/app/organizations/new'
    | '/app/library'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/check-email'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/accept-invitation/$invitationId'
    | '/app/admin'
    | '/app/audit'
    | '/app/bulk'
    | '/app/editor'
    | '/app/gallery'
    | '/app/members'
    | '/app/shares'
    | '/app/verify'
    | '/share/$token'
    | '/app/'
    | '/app/library/$watermarkId'
    | '/app/library/new'
    | '/app/organizations/new'
    | '/app/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/bulk': {
      id: '/app/bulk'
      path: '/bulk'
      fullPath: '/app/bulk'
      preLoaderRoute: typeof AppBulkRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/gallery': {
      id: '/app/gallery'
      path: '/gallery'
      fullPath: '/app/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/members': {
      id: '/app/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppMembersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/shares': {
      id: '/app/shares'
      path: '/shares'
      fullPath: '/app/shares'
      preLoaderRoute: typeof AppSharesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/verify': {
      id: '/app/verify'
      path: '/verify'
      fullPath: '/app/verify'
      preLoaderRoute: typeof AppVerifyRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/library/': {
      id: '/app/library/'
      path: '/library'
      fullPath: '/app/library/'
      preLoaderRoute: typeof AppLibraryIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/library/$watermarkId': {
      id: '/app/library/$watermarkId'
      path: '/library/$watermarkId'
      fullPath: '/app/library/$watermarkId'
      preLoaderRoute: typeof AppLibraryWatermarkIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/library/new': {
      id: '/app/library/new'
      path: '/library/new'
      fullPath: '/app/library/new'
      preLoaderRoute: typeof AppLibraryNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/organizations/new': {
      id: '/app/organizations/new'
      path: '/organizations/new'
      fullPath: '/app/organizations/new'
      preLoaderRoute: typeof AppOrganizationsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAuditRoute: typeof AppAuditRoute
  AppBulkRoute: typeof AppBulkRoute
  AppEditorRoute: typeof AppEditorRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppMembersRoute: typeof AppMembersRoute
  AppSharesRoute: typeof AppSharesRoute
  AppVerifyRoute: typeof AppVerifyRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLibraryWatermarkIdRoute: typeof AppLibraryWatermarkIdRoute
  AppLibraryNewRoute: typeof AppLibraryNewRoute
  AppOrganizationsNewRoute: typeof AppOrganizationsNewRoute
  AppLibraryIndexRoute: typeof AppLibraryIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAuditRoute: AppAuditRoute,
  AppBulkRoute: AppBulkRoute,
  AppEditorRoute: AppEditorRoute,
  AppGalleryRoute: AppGalleryRoute,
  AppMembersRoute: AppMembersRoute,
  AppSharesRoute: AppSharesRoute,
  AppVerifyRoute: AppVerifyRoute,
  AppIndexRoute: AppIndexRoute,
  AppLibraryWatermarkIdRoute: AppLibraryWatermarkIdRoute,
  AppLibraryNewRoute: AppLibraryNewRoute,
  AppOrganizationsNewRoute: AppOrganizationsNewRoute,
  AppLibraryIndexRoute: AppLibraryIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
